---
title: "EDM Notebook 1.3"
output: html_notebook
---

```{r Grundger??st}
library("igraph") # laden des igraph-objekts
library("visNetwork")


# GRUNDGER??ST (EDGELIST + NODELIST)
edges <- read.csv("EDM-Edgelist-3.9.csv", header = T, as.is = T)
edges

nodes <- read.csv("EDM-Nodelist-3.2.csv", header = T, as.is = T)
nodes

# Erstellung der Matrix der Edge- und Nodelist (keine Ahnung was uns das bringt)
edges=as.matrix(edges)
as.matrix(edges)
edgematrix <- as.matrix(edges)


nl=as.matrix(nodes)
as.matrix(nl)

# Name zuordnen
edm <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=F) #oder d=edgematrix
edm

# Auseinanderzerren
coords <- layout_with_kk(edm)

# Ausf??hren
plot(edm, 
          layout=layout_with_kk, 
          rescale=FALSE, ylim = c(-4.0,4.0), xlim = c(-4.0,4.0), asp=0,
          edge.arrow.size=.2, 
          vertex.label=NA,
          vertex.label.color="darkblue",
          vertex.color="lightgrey",
          main="Ein Deutsches M??dchen",
          sub="Bachmann, Dengler, Dillmann, Hommel, L??tgens, Senftl"
     )
  
```

```{r Visualisierung nach four-mode Netzwerk}

# Nazi-weight vom Gesamtnetzwerk visualisiert
V(edm)[(V(edm)$type=="1")]$shape <- "circle"
V(edm)[(V(edm)$type=="2")]$shape <- "circle"
V(edm)[(V(edm)$type=="3")]$shape <- "square"
V(edm)[(V(edm)$type=="4")]$shape <- "square"

shapes()

plot(edm, vertex.label=NA)

```



```{r Ego HBS}

# Kantenfarben zur??cksetzen
E(edm)[(E(edm)$familyweight > "1" )]$color <- "grey"
E(edm)[(E(edm)$familyweight < "5" )]$color <- "grey"

# Heidis Ego-Netzwerk, Stufe 1, visualisiert nach nazi-weight
EgoHBS <- make_ego_graph(edm, order=1, c("Heidi Benneckenstein"))
class(EgoHBS)
V(EgoHBS[[1]])[(V(EgoHBS[[1]])$naziweight=="0")]$color <- "#4F0500"
V(EgoHBS[[1]])[(V(EgoHBS[[1]])$naziweight=="1")]$color <- "#8F0900"
V(EgoHBS[[1]])[(V(EgoHBS[[1]])$naziweight=="2")]$color <- "#C20C00"
V(EgoHBS[[1]])[(V(EgoHBS[[1]])$naziweight=="3")]$color <- "#FF0F00"
V(EgoHBS[[1]])[(V(EgoHBS[[1]])$naziweight=="6")]$color <- "grey"

#E(EgoHBS[[1]])[(E(EgoHBS[[1]])$family.weight=="1")]$color <- "green"

class(EgoHBS)
plot(EgoHBS[[1]], vertex.label=NA)

# Nazi-weight vom Gesamtnetzwerk visualisiert
V(edm)[(V(edm)$naziweight=="0")]$color <- "#4F0500"
V(edm)[(V(edm)$naziweight=="1")]$color <- "#8F0900"
V(edm)[(V(edm)$naziweight=="2")]$color <- "#C20C00"
V(edm)[(V(edm)$naziweight=="3")]$color <- "#FF0F00"
V(edm)[(V(edm)$naziweight=="6")]$color <- "grey"

plot(edm, vertex.label=NA)
```

```{r Visualisierung nach Zeit und FamilyWeight, innerer Kreis, EgoNetzwerk}

V(edm)[(V(edm)$naziweight >="0")]$color <- "gold"

FruheKindheit <- subgraph.edges(edm, E(edm)[age == "1"])
FruheKindheit

Kindheit <- subgraph.edges(edm, E(edm)[age == "2"])
Kindheit
Pubertat <- subgraph.edges(edm, E(edm)[age == "3"])
Pubertat
Jugend <- subgraph.edges(edm, E(edm)[age == "4"])
Jugend
Erwachsen <- subgraph.edges(edm, E(edm)[age == "5"])
Erwachsen

par(mfrow=c(3,2), mar=c(0,0,2,2))

EgoHBSFK <- make_ego_graph(FruheKindheit, order=1, c("Heidi Benneckenstein"))
class(EgoHBSFK)

plot(EgoHBSFK[[1]], delete_edges(EgoHBSFK, E(EgoHBSFK)[familyweight>"1"]))
#EgoHBSFK2 <- delete_edges(EgoHBSFK, E(EgoHBSFK)[familyweight>"1"])

EgoHBSK <- make_ego_graph(Kindheit, order=1, c("Heidi Benneckenstein"))

EgoHBSP <- make_ego_graph(Pubertat, order=1, c("Heidi Benneckenstein"))

EgoHBSJ <- make_ego_graph(Jugend, order=1, c("Heidi Benneckenstein"))

EgoHBSE <- make_ego_graph(Erwachsen, order=1, c("Heidi Benneckenstein"))



plot(FruheKindheit, layout=layout.grid, vertex.label=NA, main="Fr??he Kindheit")
plot(Kindheit, layout=layout.grid, vertex.label=NA, main="Kindheit")
plot(Pubertat, layout=layout.grid, vertex.label=NA, main="Pubert??t")
plot(Jugend, layout=layout.grid, vertex.label=NA, main="Jugend")
plot(Erwachsen, layout=layout.grid, vertex.label=NA, main="Erwachsen")



```


```{r Sandkasten}

#HBSN <- make_ego_graph(edm, order = 1, nodes = V(edm)$name == "HBS", mode = "all")
#HBSN
#plot(HBSN[[1]]) 

hi <- incident(edm, V(edm)[name=="HBS"], mode="all")
hi
plot(hi)

```



```{r Teilnetzwerke, hier ist das Hauptproblem}


FruheKindheit <- subgraph.edges(edm, E(edm)[age == "1"])
FruheKindheit
Kindheit <- subgraph.edges(edm, E(edm)[age == "2"])
Kindheit
Pubertat <- subgraph.edges(edm, E(edm)[age == "3"])
Pubertat
Jugend <- subgraph.edges(edm, E(edm)[age == "4"])
Jugend
Erwachsen <- subgraph.edges(edm, E(edm)[age == "5"])
Erwachsen

par(mfrow=c(3,2), mar=c(0,0,2,2))

plot(FruheKindheit, layout=layout.grid, vertex.label=NA, main="Fr??he Kindheit")
plot(Kindheit, layout=layout.grid, vertex.label=NA, main="Kindheit")
plot(Pubertat, layout=layout.grid, vertex.label=NA, main="Pubert??t")
plot(Jugend, layout=layout.grid, vertex.label=NA, main="Jugend")
plot(Erwachsen, layout=layout.grid, vertex.label=NA, main="Erwachsen")


```

```{r Visualisierung nach Zeit, wer wie eng Beziehung}

# alle Knoten nach naziweight zur??ckgesetzt
V(edm)[(V(edm)$naziweight >"0")]$color <- "gold"

FruheKindheit <- subgraph.edges(edm, E(edm)[age == "1"])
FruheKindheit
Kindheit <- subgraph.edges(edm, E(edm)[age == "2"])
Kindheit
Pubertat <- subgraph.edges(edm, E(edm)[age == "3"])
Pubertat
Jugend <- subgraph.edges(edm, E(edm)[age == "4"])
Jugend
Erwachsen <- subgraph.edges(edm, E(edm)[age == "5"])
Erwachsen


E(edm)[(E(edm)$familyweight=="1")]$color <- "blue"
E(edm)[(E(edm)$familyweight=="2")]$color <- "darkcyan"
E(edm)[(E(edm)$familyweight=="3")]$color <- "coral1"
E(edm)[(E(edm)$familyweight=="4")]$color <- "red"
E(edm)[(E(edm)$familyweight=="5")]$color <- "orange"
E(edm)[(E(edm)$familyweight=="6")]$color <- "pink"

par(mfrow=c(3,2), mar=c(0,0,2,2))

plot(FruheKindheit, layout=layout.grid, vertex.label=NA, main="Fr??he Kindheit")
plot(Kindheit, layout=layout.grid, vertex.label=NA, main="Kindheit")
plot(Pubertat, layout=layout.grid, vertex.label=NA, main="Pubert??t")
plot(Jugend, layout=layout.grid, vertex.label=NA, main="Jugend")
plot(Erwachsen, layout=layout.grid, vertex.label=NA, main="Erwachsen")

ecount(FruheKindheit)
ecount(Kindheit)
ecount(Pubertat)
ecount(Jugend)
ecount(Erwachsen)

vcount(Jugend)
vcount(Erwachsen)

```


```{r Visualisierung nach Personengruppen und ihrer Enge der Beziehung}

# Zur??cksetzen der Farben, weil vorhin rot war Nazi-Weight
V(edm)[(V(edm)$naziweight=="0")]$color <- "gold"
V(edm)[(V(edm)$naziweight=="1")]$color <- "gold"
V(edm)[(V(edm)$naziweight=="2")]$color <- "gold"
V(edm)[(V(edm)$naziweight=="3")]$color <- "gold"
V(edm)[(V(edm)$naziweight=="6")]$color <- "gold"

E(edm)[(E(edm)$familyweight=="1")]$color <- "green"
E(edm)[(E(edm)$familyweight=="2")]$color <- "red"
E(edm)[(E(edm)$familyweight=="3")]$color <- "blue"
E(edm)[(E(edm)$familyweight=="4")]$color <- "yellow"
E(edm)[(E(edm)$familyweight=="5")]$color <- "orange"
E(edm)[(E(edm)$familyweight=="6")]$color <- "pink"

Familie <- subgraph.edges(edm, E(edm)[familyrelation == "1"])
Familie
Bekannte <- subgraph.edges(edm, E(edm)[familyrelation == "2"])
Bekannte
Organisation <- subgraph.edges(edm, E(edm)[familyrelation == "3"])
Organisation
Kultur <- subgraph.edges(edm, E(edm)[familyrelation == "4"])
Kultur

par(mfrow=c(2,2), mar=c(0,0,2,2))

plot(Familie, layout=layout.grid, vertex.label=NA, main="Familie")
plot(Bekannte, layout=layout.grid, vertex.label=NA, main="Bekannte")
plot(Organisation, layout=layout.grid, vertex.label=NA, main="Organisation")
plot(Kultur, layout=layout.grid, vertex.label=NA, main="Kultur")

```


```{r Bouncy Ansicht}
library("visNetwork") #Library Visnetwork laden
# wenn das Paket nicht geladen wird, muessen Sie es vorher installieren!

# igraph nach VisNetwork importieren
# s bezieht sich hier auf unser vorher erstelltes Netzwerk
toVisNetworkData(edm, idToLabel = TRUE) 

# degrees berechnen
degree(edm) 

# statische Visualisierung
visIgraph(edm)


```
